# Generated by Django 4.2 on 2023-05-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_favoritepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='Ручная проверка'),
        ),
    ]
